// import bcrypt from 'bcryptjs';
//使用bcrypt加密使用者密碼
const bcrypt = require('bcryptjs'); //
const data = {
  users: [
    {
      name: 'Eliot',
      email: 'a7868783@gmail.com',
      // 使用bcryptjs來加密密碼
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: '經典原味銅鑼燒1入',
      slug: '經典原味銅鑼燒',
      category: '銅鑼燒',
      image: '/images/p1.jpg',
      price: 50,
      countInStock: 10,
      numReviews: 10,
      rating: 5,
      description: '高雄銅鑼燒',
    },
    {
      
      // _id: '2',
      name: '红薯饅頭1入',
      slug: '红薯饅頭1入',
      category: '饅頭',
      image: '/images/p2.jpg',
      price: 50,
      countInStock: 20,
      numReviews: 10,
      rating: 4.5,
      description: '高雄饅頭',
    },
    {
      // _id: '3',
      name: '草莓大福1入',
      slug: '草莓大福1入',
      category: '大福',
      image: '/images/p3.jpg',
      price: 50,
      countInStock: 0,
      numReviews: 10,
      rating: 3.9,
      description: '高雄大福',
    },
    {
      // _id: '4',
      name: '梅酒羊羹1入',
      slug: '梅酒羊羹1入',
      category: '羊羹',
      image: '/images/p4.jpg',
      price: 50,
      countInStock: 15,
      numReviews: 10,
      rating: 3.4,
      description: '高雄羊羹',
    },
    {
      // _id: '5'...,
      name: '奇異果大福1入',
      slug: '奇異果大福1入',
      category: '大福',
      image: '/images/p5.jpg',
      price: 50,
      countInStock: 7,
      numReviews: 30,
      rating: 4.4,
      description: '高雄大福',
    },
    {
      // _id: '4',
      name: '艾草羊羹1入',
      slug: '艾草羊羹1入',
      category: '羊羹',
      image: '/images/6.jpg',
      price: 70,
      countInStock: 14,
      numReviews: 20,
      rating: 2.4,
      description: '高雄羊羹',
    },
    {
      // _id: '4',
      name: '梅酒羊羹1入',
      slug: '梅酒羊羹1入',
      category: '羊羹',
      image: '/images/p7.jpg',
      price: 50,
      countInStock: 15,
      numReviews: 10,
      rating: 3.4,
      description: '高雄羊羹',
    },
    {
      // _id: '4',
      name: '檸檬水饅頭1入',
      slug: '檸檬水饅頭1入',
      category: '水饅頭',
      image: '/images/p8.jpg',
      price: 40,
      countInStock: 12,
      numReviews: 31,
      rating: 4.2,
      description: '高雄水饅頭',
    },
  ],
};

module.exports = data;
